name = "popen-fortran"
author = "Jacob Williams"
maintainer = "Jacob Williams"
copyright = "Copyright (c) 2014-2023 Jacob Williams"
license = "BSD-3"
description = "Simple Fortran module for popen"
homepage = "https://github.com/jacobwilliams/popen-fortran"

[build]
auto-executables = true
auto-examples = true
auto-tests = true

[preprocess]
cpp.suffixes = ["F90", "f90"]
# cpp.macros = ["_WIN32"]

[library]
source-dir = "src"

[install]
library = true